runtime: nodejs18

env_variables:
  # Set environment variables here if needed
  NODE_ENV: production

automatic_scaling:
  # Configure scaling options for your app
  min_instances: 1
  max_instances: 5
  target_cpu_utilization: 0.65

handlers:
  # Configure URL routing and request handling
  - url: /.*
    script: auto
